"""
Smart Waste Classification - YOLOv11n Training Script

Subject: IPA (Image Processing and Applications)

Target Model: YOLOv11n (Ultralytics)

This script trains YOLOv11n on the merged Smart Waste dataset.

Target Classes:
0 - E_waste
1 - Medical_waste
2 - Hazardous_waste
3 - Chemical_waste
4 - Plastic_waste

Training configuration:
- YOLOv11n pretrained weights
- NVIDIA GPU with CUDA
- Automatic Mixed Precision (AMP)
- 640x640 image size
- 50 epochs
- Batch size 16
- Windows-safe workers
"""

import os
import sys
import shutil
import torch
from ultralytics import YOLO


# ==============================================================================
# PROJECT PATHS
# ==============================================================================

# Always use the folder containing this train.py file.
# This prevents problems when Python/VS Code is launched from another directory.

PROJECT_DIR = os.path.dirname(os.path.abspath(__file__))

# Merged dataset generated by merge_datasets.py
DATASET_DIR = os.path.join(
    PROJECT_DIR,
    "Dataset",
    "Final_merged_dataset",
    "merged"
)

# Dataset YAML
DATA_YAML = os.path.join(DATASET_DIR, "data.yaml")

# YOLO training output directory
PROJECT_NAME = os.path.join(
    PROJECT_DIR,
    "runs",
    "detect"
)

# Experiment name
EXPERIMENT_NAME = "smart_waste_yolo11n"


# ==============================================================================
# MODEL AND TRAINING PARAMETERS
# ==============================================================================

# Official pretrained YOLOv11 nano model
BASE_MODEL = "yolo11n.pt"

# Final project training
EPOCHS = 50

# YOLO image resolution
IMAGE_SIZE = 640

# RTX 2050 4 GB VRAM
BATCH_SIZE = 16

# Number of Windows dataloader workers
WORKERS = 2


# ==============================================================================
# MAIN FUNCTION
# ==============================================================================

def main():

    print("=" * 70)
    print("SMART WASTE CLASSIFICATION - YOLOv11n TRAINING")
    print("=" * 70)

    print("\nProject directory:")
    print(PROJECT_DIR)

    print("\nDataset directory:")
    print(DATASET_DIR)

    print("\nDataset YAML:")
    print(DATA_YAML)

    print("\nTraining output:")
    print(os.path.join(PROJECT_NAME, EXPERIMENT_NAME))

    print("=" * 70)


    # ==========================================================================
    # 1. CHECK DATASET
    # ==========================================================================

    if not os.path.exists(DATASET_DIR):
        print("\n[!] ERROR: Merged dataset folder not found!")
        print(f"    Expected:")
        print(f"    {DATASET_DIR}")
        print("\nPlease run merge_datasets.py first.")
        sys.exit(1)

    if not os.path.exists(DATA_YAML):
        print("\n[!] ERROR: data.yaml not found!")
        print(f"    Expected:")
        print(f"    {DATA_YAML}")
        print("\nPlease run merge_datasets.py first.")
        sys.exit(1)

    # Check train images
    train_images_dir = os.path.join(
        DATASET_DIR,
        "train",
        "images"
    )

    valid_images_dir = os.path.join(
        DATASET_DIR,
        "valid",
        "images"
    )

    test_images_dir = os.path.join(
        DATASET_DIR,
        "test",
        "images"
    )

    if not os.path.exists(train_images_dir):
        print("\n[!] ERROR: Training images folder not found!")
        print(train_images_dir)
        sys.exit(1)

    # Count images
    image_extensions = (
        ".jpg",
        ".jpeg",
        ".png",
        ".bmp",
        ".webp"
    )

    train_count = sum(
        1
        for f in os.listdir(train_images_dir)
        if f.lower().endswith(image_extensions)
    )

    valid_count = 0
    test_count = 0

    if os.path.exists(valid_images_dir):
        valid_count = sum(
            1
            for f in os.listdir(valid_images_dir)
            if f.lower().endswith(image_extensions)
        )

    if os.path.exists(test_images_dir):
        test_count = sum(
            1
            for f in os.listdir(test_images_dir)
            if f.lower().endswith(image_extensions)
        )

    print("\nMerged Dataset Check:")
    print(f"  Train images : {train_count}")
    print(f"  Valid images : {valid_count}")
    print(f"  Test images  : {test_count}")

    if train_count == 0:
        print("\n[!] ERROR: Training folder contains 0 images.")
        print("    Do not start training.")
        print("    Check merge_datasets.py output first.")
        sys.exit(1)

    print("\n[✓] Merged dataset detected successfully.")


    # ==========================================================================
    # 2. HARDWARE CHECK
    # ==========================================================================

    print("\n" + "=" * 70)
    print("HARDWARE CHECK")
    print("=" * 70)

    cuda_available = torch.cuda.is_available()

    if cuda_available:

        gpu_name = torch.cuda.get_device_name(0)

        vram = round(
            torch.cuda.get_device_properties(0).total_memory
            / (1024 ** 3),
            2
        )

        device = 0

        print(f"[✓] GPU Detected : {gpu_name}")
        print(f"[✓] VRAM         : {vram} GB")
        print(f"[✓] CUDA Device  : {device}")
        print("[✓] AMP          : Enabled")

    else:

        device = "cpu"

        print("[!] WARNING: CUDA GPU not detected.")
        print("[!] Training will run on CPU.")
        print("[!] This will be significantly slower.")


    # ==========================================================================
    # 3. TRAINING CONFIGURATION
    # ==========================================================================

    print("\n" + "=" * 70)
    print("TRAINING CONFIGURATION")
    print("=" * 70)

    print(f"  Base Model : {BASE_MODEL}")
    print(f"  Dataset    : {DATA_YAML}")
    print(f"  Epochs     : {EPOCHS}")
    print(f"  Batch Size : {BATCH_SIZE}")
    print(f"  Image Size : {IMAGE_SIZE}x{IMAGE_SIZE}")
    print(f"  Workers    : {WORKERS}")
    print(f"  Device     : {device}")
    print(f"  AMP        : True")
    print(f"  Output     : {PROJECT_NAME}")
    print(f"  Experiment : {EXPERIMENT_NAME}")

    print("=" * 70)


    # ==========================================================================
    # 4. LOAD YOLOv11n PRETRAINED MODEL
    # ==========================================================================

    print("\n[1/4] Loading YOLOv11n pretrained model...")

    try:

        model = YOLO(BASE_MODEL)

        print("[✓] YOLOv11n model loaded successfully.")

    except Exception as e:

        print("\n[!] ERROR while loading YOLOv11n:")
        print(e)
        sys.exit(1)


    # ==========================================================================
    # 5. START TRAINING
    # ==========================================================================

    print("\n[2/4] Starting YOLOv11n training...")
    print("\nTraining may take some time. Please do not close this window.\n")

    try:

        results = model.train(

            # Dataset
            data=DATA_YAML,

            # Training duration
            epochs=EPOCHS,

            # Image resolution
            imgsz=IMAGE_SIZE,

            # Batch size
            batch=BATCH_SIZE,

            # GPU/CPU
            device=device,

            # Automatic Mixed Precision
            amp=True,

            # Windows-safe dataloader workers
            workers=WORKERS,

            # Absolute output directory
            project=PROJECT_NAME,

            # Experiment name
            name=EXPERIMENT_NAME,

            # Reuse same experiment directory
            exist_ok=True,

            # Save checkpoints
            save=True,

            # Generate graphs and evaluation plots
            plots=True,

            # Save best and last checkpoints
            save_period=-1

        )

    except Exception as e:

        print("\n[!] ERROR DURING TRAINING:")
        print(e)

        print("\nPossible causes:")
        print("1. Insufficient GPU memory")
        print("2. Incorrect dataset labels")
        print("3. Invalid data.yaml")
        print("4. Missing/corrupt image")
        print("5. CUDA/PyTorch issue")

        sys.exit(1)


    # ==========================================================================
    # 6. BEST MODEL PATH
    # ==========================================================================

    best_weights_path = os.path.join(
        PROJECT_NAME,
        EXPERIMENT_NAME,
        "weights",
        "best.pt"
    )

    last_weights_path = os.path.join(
        PROJECT_NAME,
        EXPERIMENT_NAME,
        "weights",
        "last.pt"
    )

    print("\n" + "=" * 70)
    print("TRAINING FINISHED")
    print("=" * 70)

    print(f"\nBest model expected at:")
    print(best_weights_path)

    print(f"\nLast model expected at:")
    print(last_weights_path)


    # ==========================================================================
    # 7. VALIDATE BEST MODEL
    # ==========================================================================

    if not os.path.exists(best_weights_path):

        print("\n[!] ERROR: best.pt was not found.")
        print("    Training may not have completed correctly.")
        sys.exit(1)

    print("\n[3/4] Loading best.pt for final validation...")

    try:

        best_model = YOLO(best_weights_path)

        print("[✓] Best model loaded.")

        print("\nRunning validation...")

        val_metrics = best_model.val(
            data=DATA_YAML,
            imgsz=IMAGE_SIZE,
            device=device
        )

    except Exception as e:

        print("\n[!] ERROR DURING VALIDATION:")
        print(e)
        sys.exit(1)


    # ==========================================================================
    # 8. DISPLAY FINAL METRICS
    # ==========================================================================

    print("\n" + "=" * 70)
    print("FINAL MODEL PERFORMANCE")
    print("=" * 70)

    try:

        print(
            f"  mAP@0.50       : "
            f"{val_metrics.box.map50:.4f}"
        )

        print(
            f"  mAP@0.50:0.95  : "
            f"{val_metrics.box.map:.4f}"
        )

    except Exception:

        print("[!] Unable to read validation metrics.")


    # ==========================================================================
    # 9. COPY BEST MODEL TO PROJECT ROOT
    # ==========================================================================

    target_weights_path = os.path.join(
        PROJECT_DIR,
        "best.pt"
    )

    print("\n[4/4] Copying best model...")

    try:

        shutil.copy2(
            best_weights_path,
            target_weights_path
        )

        print("\n[✓] Best model successfully copied to:")

        print(f"    {target_weights_path}")

    except Exception as e:

        print("\n[!] ERROR while copying best.pt:")
        print(e)


    # ==========================================================================
    # 10. FINAL SUMMARY
    # ==========================================================================

    print("\n" + "=" * 70)
    print("TRAINING & VALIDATION COMPLETE")
    print("=" * 70)

    print("\nDataset:")
    print(f"  {DATA_YAML}")

    print("\nBest trained weights:")
    print(f"  {best_weights_path}")

    print("\nGUI-ready weights:")
    print(f"  {target_weights_path}")

    print("\nTarget classes:")
    print("  0 - E_waste")
    print("  1 - Medical_waste")
    print("  2 - Hazardous_waste")
    print("  3 - Chemical_waste")
    print("  4 - Plastic_waste")

    print("\nYou can now launch the GUI using:")
    print("  python app_gui.py")

    print("\n" + "=" * 70)


# ==============================================================================
# WINDOWS ENTRY POINT
# ==============================================================================

if __name__ == "__main__":
    main()
